configs:
  params:
    server.insecure: false

server:
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    hosts:
      - argocd.local
    tls: []

  extraArgs:
    - --insecure=false

repoServer:
  containerSecurityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
