replicaCount: 4

image:
  repository: 508591325080.dkr.ecr.us-east-1.amazonaws.com/cloudnative-app
  tag: latest
  digest: ""

serviceAccount:
  create: true
  name: app-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::508591325080:role/AppRuntimeRole-prod

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 20
  targetCPUUtilizationPercentage: 60

resources:
  requests:
    cpu: 300m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
